vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        exercises:
            uri_prefix: /uploads/files/exercises
            upload_destination: '%kernel.project_dir%/public/exercises'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
